// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: proto/pedidos.proto

package pedidospb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pedido struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Produto    string `protobuf:"bytes,2,opt,name=produto,proto3" json:"produto,omitempty"`
	Quantidade int32  `protobuf:"varint,3,opt,name=quantidade,proto3" json:"quantidade,omitempty"`
}

func (x *Pedido) Reset() {
	*x = Pedido{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pedidos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pedido) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pedido) ProtoMessage() {}

func (x *Pedido) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pedidos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pedido.ProtoReflect.Descriptor instead.
func (*Pedido) Descriptor() ([]byte, []int) {
	return file_proto_pedidos_proto_rawDescGZIP(), []int{0}
}

func (x *Pedido) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pedido) GetProduto() string {
	if x != nil {
		return x.Produto
	}
	return ""
}

func (x *Pedido) GetQuantidade() int32 {
	if x != nil {
		return x.Quantidade
	}
	return 0
}

type CriarPedidoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Produto    string `protobuf:"bytes,1,opt,name=produto,proto3" json:"produto,omitempty"`
	Quantidade int32  `protobuf:"varint,2,opt,name=quantidade,proto3" json:"quantidade,omitempty"`
}

func (x *CriarPedidoRequest) Reset() {
	*x = CriarPedidoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pedidos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CriarPedidoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriarPedidoRequest) ProtoMessage() {}

func (x *CriarPedidoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pedidos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriarPedidoRequest.ProtoReflect.Descriptor instead.
func (*CriarPedidoRequest) Descriptor() ([]byte, []int) {
	return file_proto_pedidos_proto_rawDescGZIP(), []int{1}
}

func (x *CriarPedidoRequest) GetProduto() string {
	if x != nil {
		return x.Produto
	}
	return ""
}

func (x *CriarPedidoRequest) GetQuantidade() int32 {
	if x != nil {
		return x.Quantidade
	}
	return 0
}

type CriarPedidoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pedido *Pedido `protobuf:"bytes,1,opt,name=pedido,proto3" json:"pedido,omitempty"`
}

func (x *CriarPedidoResponse) Reset() {
	*x = CriarPedidoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pedidos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CriarPedidoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CriarPedidoResponse) ProtoMessage() {}

func (x *CriarPedidoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pedidos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CriarPedidoResponse.ProtoReflect.Descriptor instead.
func (*CriarPedidoResponse) Descriptor() ([]byte, []int) {
	return file_proto_pedidos_proto_rawDescGZIP(), []int{2}
}

func (x *CriarPedidoResponse) GetPedido() *Pedido {
	if x != nil {
		return x.Pedido
	}
	return nil
}

type ListarPedidosRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListarPedidosRequest) Reset() {
	*x = ListarPedidosRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pedidos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListarPedidosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarPedidosRequest) ProtoMessage() {}

func (x *ListarPedidosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pedidos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarPedidosRequest.ProtoReflect.Descriptor instead.
func (*ListarPedidosRequest) Descriptor() ([]byte, []int) {
	return file_proto_pedidos_proto_rawDescGZIP(), []int{3}
}

type ListarPedidosResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pedidos []*Pedido `protobuf:"bytes,1,rep,name=pedidos,proto3" json:"pedidos,omitempty"`
}

func (x *ListarPedidosResponse) Reset() {
	*x = ListarPedidosResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pedidos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListarPedidosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListarPedidosResponse) ProtoMessage() {}

func (x *ListarPedidosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pedidos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListarPedidosResponse.ProtoReflect.Descriptor instead.
func (*ListarPedidosResponse) Descriptor() ([]byte, []int) {
	return file_proto_pedidos_proto_rawDescGZIP(), []int{4}
}

func (x *ListarPedidosResponse) GetPedidos() []*Pedido {
	if x != nil {
		return x.Pedidos
	}
	return nil
}

var File_proto_pedidos_proto protoreflect.FileDescriptor

var file_proto_pedidos_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x22, 0x52,
	0x0a, 0x06, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x74, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61,
	0x64, 0x65, 0x22, 0x4e, 0x0a, 0x12, 0x43, 0x72, 0x69, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x64, 0x75,
	0x74, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61, 0x64, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x64, 0x61,
	0x64, 0x65, 0x22, 0x3e, 0x0a, 0x13, 0x43, 0x72, 0x69, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64,
	0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x70, 0x65, 0x64,
	0x69, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x65, 0x64, 0x69,
	0x64, 0x6f, 0x73, 0x2e, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x52, 0x06, 0x70, 0x65, 0x64, 0x69,
	0x64, 0x6f, 0x22, 0x16, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69,
	0x64, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x42, 0x0a, 0x15, 0x4c, 0x69,
	0x73, 0x74, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x29, 0x0a, 0x07, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x2e, 0x50,
	0x65, 0x64, 0x69, 0x64, 0x6f, 0x52, 0x07, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x32, 0xa9,
	0x01, 0x0a, 0x0d, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x48, 0x0a, 0x0b, 0x43, 0x72, 0x69, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x12,
	0x1b, 0x2e, 0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x2e, 0x43, 0x72, 0x69, 0x61, 0x72, 0x50,
	0x65, 0x64, 0x69, 0x64, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x70,
	0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x2e, 0x43, 0x72, 0x69, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69,
	0x64, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x0d, 0x4c, 0x69,
	0x73, 0x74, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x12, 0x1d, 0x2e, 0x70, 0x65,
	0x64, 0x69, 0x64, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69,
	0x64, 0x6f, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x65, 0x64,
	0x69, 0x64, 0x6f, 0x73, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x61, 0x72, 0x50, 0x65, 0x64, 0x69, 0x64,
	0x6f, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f,
	0x70, 0x65, 0x64, 0x69, 0x64, 0x6f, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_pedidos_proto_rawDescOnce sync.Once
	file_proto_pedidos_proto_rawDescData = file_proto_pedidos_proto_rawDesc
)

func file_proto_pedidos_proto_rawDescGZIP() []byte {
	file_proto_pedidos_proto_rawDescOnce.Do(func() {
		file_proto_pedidos_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pedidos_proto_rawDescData)
	})
	return file_proto_pedidos_proto_rawDescData
}

var file_proto_pedidos_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_pedidos_proto_goTypes = []interface{}{
	(*Pedido)(nil),                // 0: pedidos.Pedido
	(*CriarPedidoRequest)(nil),    // 1: pedidos.CriarPedidoRequest
	(*CriarPedidoResponse)(nil),   // 2: pedidos.CriarPedidoResponse
	(*ListarPedidosRequest)(nil),  // 3: pedidos.ListarPedidosRequest
	(*ListarPedidosResponse)(nil), // 4: pedidos.ListarPedidosResponse
}
var file_proto_pedidos_proto_depIdxs = []int32{
	0, // 0: pedidos.CriarPedidoResponse.pedido:type_name -> pedidos.Pedido
	0, // 1: pedidos.ListarPedidosResponse.pedidos:type_name -> pedidos.Pedido
	1, // 2: pedidos.PedidoService.CriarPedido:input_type -> pedidos.CriarPedidoRequest
	3, // 3: pedidos.PedidoService.ListarPedidos:input_type -> pedidos.ListarPedidosRequest
	2, // 4: pedidos.PedidoService.CriarPedido:output_type -> pedidos.CriarPedidoResponse
	4, // 5: pedidos.PedidoService.ListarPedidos:output_type -> pedidos.ListarPedidosResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_pedidos_proto_init() }
func file_proto_pedidos_proto_init() {
	if File_proto_pedidos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pedidos_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pedido); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pedidos_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CriarPedidoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pedidos_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CriarPedidoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pedidos_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListarPedidosRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pedidos_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListarPedidosResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pedidos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pedidos_proto_goTypes,
		DependencyIndexes: file_proto_pedidos_proto_depIdxs,
		MessageInfos:      file_proto_pedidos_proto_msgTypes,
	}.Build()
	File_proto_pedidos_proto = out.File
	file_proto_pedidos_proto_rawDesc = nil
	file_proto_pedidos_proto_goTypes = nil
	file_proto_pedidos_proto_depIdxs = nil
}
